"""LLM narrative with a number guard and a template fallback.

Flow: cache lookup -> call -> parse JSON -> validate (retry once with the error) ->
number guard -> cache. Any failure (no key, API error, timeout, bad JSON, guard
failure) returns the deterministic template instead, so a report is always produced.
The LLM only ever receives ``facts.json`` and is asked to write prose, never to compute.
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

from openai import OpenAI
from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator

from mre.config import LLMConfig
from mre.facts import canonical_json, facts_hash

log = logging.getLogger(__name__)

AI_DISCLOSURE = "Summary generated by an AI model from the numbers in this report."
TEMPLATE_DISCLOSURE = (
    "Summary generated from a fixed template because the AI summary was unavailable."
)

# --- output schema ----------------------------------------------------------------

_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+(?=[A-Z0-9\"'(])")


def count_sentences(text: str) -> int:
    return len([s for s in _SENTENCE_SPLIT.split(text.strip()) if s])


class NarrativeOutput(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    summary: str = Field(min_length=1)
    findings: list[str] = Field(min_length=3, max_length=3)
    checks: list[str] = Field(min_length=3, max_length=3)

    @field_validator("summary")
    @classmethod
    def _three_to_five_sentences(cls, value: str) -> str:
        n = count_sentences(value)
        if not 3 <= n <= 5:
            raise ValueError(f"summary must have 3 to 5 sentences, got {n}")
        return value

    @field_validator("findings", "checks")
    @classmethod
    def _non_empty_items(cls, value: list[str]) -> list[str]:
        if any(not item.strip() for item in value):
            raise ValueError("items must be non-empty strings")
        return value

    def texts(self) -> list[str]:
        return [self.summary, *self.findings, *self.checks]


def parse_response(text: str) -> NarrativeOutput:
    """Parse model text into the schema; tolerates code fences around the JSON."""
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end <= start:
        raise ValueError("no JSON object found in the response")
    return NarrativeOutput.model_validate(json.loads(text[start : end + 1]))


# --- number guard -----------------------------------------------------------------

ALLOWED_NUMBERS = frozenset({2020.0, 2021.0})  # years
_WEEK_LABEL = re.compile(r"\b\d{4}-W\d{2}\b")
_ISO_DATE = re.compile(r"\b\d{4}-\d{2}-\d{2}\b")
_NUMBER = re.compile(
    r"(?<![A-Za-z0-9.])"
    r"(?P<int>\d{1,3}(?:,\d{3})+|\d+)"
    r"(?P<dec>\.\d+)?"
    r"(?P<suffix>[kKmM](?![A-Za-z]))?"
)
_MULTIPLIER = {"k": 1e3, "m": 1e6}


@dataclass(frozen=True)
class NumberToken:
    text: str
    value: float
    tolerance: float  # half a unit of the last written digit


def extract_numbers(text: str) -> list[NumberToken]:
    """Numbers in prose, ignoring week labels and ISO dates. Signs are dropped."""
    text = _ISO_DATE.sub(" ", _WEEK_LABEL.sub(" ", text))
    tokens = []
    for m in _NUMBER.finditer(text):
        decimals = len(m.group("dec") or ".") - 1
        multiplier = _MULTIPLIER.get((m.group("suffix") or "").lower(), 1.0)
        value = float(m.group("int").replace(",", "") + (m.group("dec") or "")) * multiplier
        tokens.append(NumberToken(m.group(0), value, 0.5 * 10**-decimals * multiplier))
    return tokens


def fact_numbers(facts: Any) -> set[float]:
    """Every numeric value in facts.json, as absolute values."""
    found: set[float] = set()
    if isinstance(facts, dict):
        for v in facts.values():
            found |= fact_numbers(v)
    elif isinstance(facts, list):
        for v in facts:
            found |= fact_numbers(v)
    elif isinstance(facts, int | float) and not isinstance(facts, bool):
        found.add(abs(float(facts)))
    return found


@dataclass(frozen=True)
class GuardResult:
    ok: bool
    unmatched: list[str]


def check_numbers(output: NarrativeOutput, facts: dict[str, Any]) -> GuardResult:
    known = fact_numbers(facts)
    unmatched = []
    for text in output.texts():
        for token in extract_numbers(text):
            if token.value in ALLOWED_NUMBERS and token.tolerance == 0.5:
                continue
            if not any(abs(token.value - v) <= token.tolerance + 1e-9 for v in known):
                unmatched.append(token.text)
    return GuardResult(ok=not unmatched, unmatched=unmatched)


# --- template fallback --------------------------------------------------------------

_METRIC_LABELS = {
    "sessions": "sessions",
    "purchases": "purchases",
    "revenue": "revenue",
    "spend": "spend",
    "conversion_rate": "conversion rate",
    "cost_per_session": "cost per session",
    "cpa": "CPA",
    "revenue_share": "revenue share",
    "missing_revenue_share": "share of purchases without revenue",
}
_MONEY = frozenset({"revenue", "spend", "aov", "cpa", "cost_per_session"})


def _label(name: str) -> str:
    return name.replace("_", " ")


def _money(v: float) -> str:
    return f"${v:,.2f}"


def _plain(v: float) -> str:
    return f"{v:,.0f}" if float(v).is_integer() else f"{v:,.2f}"


def _fmt_metric(metric: str, v: float | None, unit: str | None) -> str:
    if v is None:
        return "n/a"
    if unit == "%":
        return f"{v:.1f}%"
    return _money(v) if metric in _MONEY else _plain(v)


def _moved(pct: float) -> str:
    if pct > 0:
        return f"rose {pct:.1f}%"
    if pct < 0:
        return f"fell {abs(pct):.1f}%"
    return "was unchanged"


def _anomaly_finding(a: dict[str, Any]) -> str:
    channel, metric = _label(a["channel"]), _METRIC_LABELS.get(a["metric"], _label(a["metric"]))
    simulated = " (simulated)" if a["simulated"] else ""
    rule = a["rule"]
    if rule == "tracking_gap":
        return (
            f"{a['value']:.1f}% of purchases had no revenue recorded, "
            "which points to a tracking gap rather than lost sales."
        )
    if rule == "paid_spend_no_purchases":
        return f"{channel.capitalize()} had simulated spend but no purchases this week."
    if rule == "cost_increase":
        return (
            f"Simulated {metric} for {channel} rose {a['change_pct']:.1f}% week over week "
            f"to {_fmt_metric(a['metric'], a['value'], a['unit'])}."
        )
    if rule == "conversion_drop":
        return (
            f"Conversion rate for {channel} fell {abs(a['change_pct']):.1f}% week over week "
            "while sessions were stable."
        )
    if rule == "revenue_share_shift":
        return (
            f"The {channel} share of revenue moved {abs(a['change_pp']):.1f} percentage points "
            f"to {a['value']:.1f}%."
        )
    context = ""
    if (a.get("seasonal_context") or "").startswith("baseline"):
        context = " (its comparison window includes holiday-season days)"
    elif a.get("seasonal_context"):
        context = f", during the {a['seasonal_context']}"
    return (
        f"{channel.capitalize()} {metric}{simulated} on {a['when']} was "
        f"{_fmt_metric(a['metric'], a['value'], a['unit'])} against a typical "
        f"{_fmt_metric(a['metric'], a['baseline'], a['unit'])}{context}."
    )


_RULE_CHECKS = {
    "tracking_gap": "Check the purchase tracking setup, since revenue was not recorded for "
    "part of this week's purchases.",
    "paid_spend_no_purchases": "Check paid search tagging and conversion tracking, because "
    "simulated spend produced no recorded purchases.",
    "cost_increase": "Review the simulated paid search cost trend before changing budgets.",
    "revenue_share_shift": "Compare channel attribution with the previous week to understand "
    "the shift in revenue share.",
    "conversion_drop": "Look at landing pages and checkout for the channel whose conversion "
    "rate fell while traffic held steady.",
}


def template_narrative(facts: dict[str, Any]) -> NarrativeOutput:
    """Deterministic narrative that uses only values from facts (so it passes the guard)."""
    t, week, dq = facts["totals"], facts["report_week"], facts["data_quality"]
    summary = [
        f"In {week}, the store recorded {t['sessions']:,} sessions, {t['purchases']:,} "
        f"purchases and {_money(t['revenue'])} in revenue."
    ]
    if facts["previous_week"] and t["wow_revenue_pct"] is not None:
        sessions_move = (
            f" and sessions {_moved(t['wow_sessions_pct'])}"
            if t["wow_sessions_pct"] is not None
            else ""
        )
        summary.append(
            f"Revenue {_moved(t['wow_revenue_pct'])}{sessions_move} compared with "
            f"{facts['previous_week']}."
        )
    else:
        summary.append("There is no previous complete week to compare with.")
    aov = f" and the average order value was {_money(t['aov'])}" if t["aov"] is not None else ""
    summary.append(f"The overall conversion rate was {t['conversion_rate_pct']:.1f}%{aov}.")
    summary.append("Ad spend and spend-based metrics in this report are simulated.")
    missing = dq["missing_revenue_share_pct"]
    if missing is not None and missing >= 20:
        summary.append(
            f"Revenue may be understated because {dq['purchases_missing_revenue']:,} "
            "purchases had no revenue recorded."
        )

    findings: list[str] = [_anomaly_finding(a) for a in facts["anomalies"][:2]]
    for m in facts["top_movers"]:
        if m["change_pct"] is not None:
            findings.append(
                f"{_label(m['channel']).capitalize()} revenue changed from {_money(m['from'])} "
                f"to {_money(m['to'])} ({m['change_pct']:+.1f}%)."
            )
    for c in facts["channels"]:
        if c["revenue_share_pct"] is not None:
            findings.append(
                f"{_label(c['channel']).capitalize()} contributed {c['revenue_share_pct']:.1f}% "
                f"of revenue from {c['session_share_pct']:.1f}% of sessions."
            )

    checks = [_RULE_CHECKS[a["rule"]] for a in facts["anomalies"] if a["rule"] in _RULE_CHECKS]
    seasonal = [a.get("seasonal_context") or "" for a in facts["anomalies"]]
    if any(c and not c.startswith("baseline") for c in seasonal):
        checks.append(
            "Compare holiday-period results with the same period in earlier data before "
            "treating seasonal peaks as unusual."
        )
    checks += [
        f"Review the {dq['unknown_channel_session_share_pct']:.1f}% of sessions with an unknown "
        "channel to improve attribution.",
        "Confirm the channel mapping still matches current campaign tagging.",
        "Wait for the next complete week before acting on single-week changes.",
    ]
    return NarrativeOutput(
        summary=" ".join(summary),
        findings=list(dict.fromkeys(findings))[:3],
        checks=list(dict.fromkeys(checks))[:3],
    )


# --- LLM call ------------------------------------------------------------------------


@dataclass
class NarrativeResult:
    output: NarrativeOutput
    source: Literal["llm", "cache", "fallback"]
    fallback_reason: str | None = None
    unmatched_numbers: list[str] = field(default_factory=list)
    input_tokens: int = 0
    output_tokens: int = 0
    cost_usd: float = 0.0

    @property
    def disclosure(self) -> str:
        return TEMPLATE_DISCLOSURE if self.source == "fallback" else AI_DISCLOSURE


def make_client(cfg: LLMConfig, api_key: str) -> OpenAI:
    return OpenAI(
        base_url=cfg.base_url, api_key=api_key, timeout=cfg.timeout_seconds, max_retries=1
    )


def cache_key(facts: dict[str, Any], cfg: LLMConfig, system_prompt: str) -> str:
    prompt_hash = hashlib.sha256(system_prompt.encode("utf-8")).hexdigest()[:12]
    material = f"{cfg.model}|{cfg.temperature}|{prompt_hash}|{facts_hash(facts)}"
    return hashlib.sha256(material.encode("utf-8")).hexdigest()


def _estimate_cost(cfg: LLMConfig, input_tokens: int, output_tokens: int) -> float:
    return (
        input_tokens * cfg.input_price_per_mtok + output_tokens * cfg.output_price_per_mtok
    ) / 1_000_000


def _fallback(facts: dict[str, Any], reason: str, **kwargs: Any) -> NarrativeResult:
    log.warning("Using template narrative: %s", reason)
    return NarrativeResult(template_narrative(facts), "fallback", reason, **kwargs)


def generate_narrative(
    facts: dict[str, Any],
    cfg: LLMConfig,
    api_key: str | None,
    client: Any | None = None,
) -> NarrativeResult:
    """Return a guarded LLM narrative, a cached one, or the template fallback."""
    system_prompt = Path(cfg.system_prompt_path).read_text(encoding="utf-8")
    cache_path = Path(cfg.cache_dir) / f"{cache_key(facts, cfg, system_prompt)}.json"

    if cache_path.exists():
        try:
            cached = NarrativeOutput.model_validate_json(cache_path.read_text(encoding="utf-8"))
            if check_numbers(cached, facts).ok:
                log.info("Narrative loaded from cache %s", cache_path.name)
                return NarrativeResult(cached, "cache")
        except (ValidationError, ValueError):
            log.warning("Ignoring unreadable narrative cache %s", cache_path.name)

    if client is None:
        if not api_key:
            return _fallback(facts, "no OPENROUTER_API_KEY configured")
        client = make_client(cfg, api_key)

    messages: list[Any] = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": "facts = " + json.dumps(facts, indent=1, sort_keys=True)},
    ]
    input_tokens = output_tokens = 0
    output: NarrativeOutput | None = None
    error = ""
    for attempt in range(1 + cfg.max_retries):
        try:
            response = client.chat.completions.create(
                model=cfg.model, temperature=cfg.temperature, messages=messages
            )
        except Exception as exc:  # any API/network failure must not stop the report
            return _fallback(
                facts,
                f"API call failed: {type(exc).__name__}: {exc}",
                input_tokens=input_tokens,
                output_tokens=output_tokens,
            )
        if response.usage is not None:
            input_tokens += response.usage.prompt_tokens or 0
            output_tokens += response.usage.completion_tokens or 0
        content = response.choices[0].message.content or ""
        try:
            output = parse_response(content)
            break
        except (ValidationError, ValueError) as exc:
            error = str(exc).splitlines()[0] if str(exc) else type(exc).__name__
            log.warning("Invalid LLM response (attempt %d): %s", attempt + 1, error)
            messages += [
                {"role": "assistant", "content": content},
                {
                    "role": "user",
                    "content": f"Your reply was invalid: {exc}. Reply again with valid JSON "
                    "only, following the required schema.",
                },
            ]

    cost = _estimate_cost(cfg, input_tokens, output_tokens)
    log.info(
        "LLM usage: %d input tokens, %d output tokens, estimated cost $%.5f",
        input_tokens,
        output_tokens,
        cost,
    )
    usage: dict[str, Any] = {
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "cost_usd": cost,
    }
    if output is None:
        return _fallback(facts, f"invalid JSON after retries: {error}", **usage)

    guard = check_numbers(output, facts)
    if not guard.ok:
        log.warning("Number guard rejected: %s", ", ".join(guard.unmatched))
        return _fallback(facts, "number guard failed", unmatched_numbers=guard.unmatched, **usage)

    cache_path.parent.mkdir(parents=True, exist_ok=True)
    cache_path.write_text(output.model_dump_json(indent=1), encoding="utf-8")
    return NarrativeResult(output, "llm", **usage)


def facts_for_prompt(facts: dict[str, Any]) -> str:
    """Exact text the model sees (useful for debugging prompts)."""
    return canonical_json(facts)
